### ISSUE TITLE
Add margin to Post headings

### ISSUE THREAD

**Issue by Kechr** [msd-d/PetHub#21]
The headings are at the edge of the screen.
![image](https://user-images.githubusercontent.com/55458479/140036995-3e1e8d92-eef5-4a75-b935-85aa405ef31a.png)

**Comment by Joergenson** [comment]
Old version again?? Should be fixed after #18

**Comment by Joergenson** [comment]
Also move issues to the pull request about the view instead ❤️

**Comment by Kechr** [comment]
> Also move issues to the pull request about the view instead heart

Well, it has nothing to do with the functionality of the view. Don't bloat your PRs.

**Comment by Joergenson** [comment]
While that is true getting things merged takes ages so I would want it in #18. The image picker at least
