### ISSUE TITLE
Buttons are cramped on iOS

### ISSUE THREAD

**Issue by SnaBe** [msd-d/PetHub#36]
The gradient buttons seem to be cramped on iOS devices as seen below the note. 
* **Note**: This might not be an issue for only gradient buttons, but all types.

![cramped_button](https://user-images.githubusercontent.com/16469268/140625907-0d999ce9-b79e-4cc4-ad21-22ceb51a4764.png)

**Comment by Joergenson** [comment]
Will look into it tomorrow :-)

**Comment by Kechr** [comment]
`overflow: "hidden"`might do the trick.
